### ISSUE TITLE
my role will be unit tests

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#10]
I am already engaged in monero with unit tests. I have been doing a ton of python unit testing and mocking at work. I plan on using this to learn as much as I can about these two code bases. This will keep me out of others way as well. I can help with other things but that will be my focus.

**Comment by drparadoxical** [comment]
Godspeed. As long as it doesn't slow you down or get in the way of your efforts, would you part the unit testing related work and be sure to take contrib/{epee|fuzz_testing|rlwrap} and external/{db_drivers|miniupnpc} into consideration?

I believe you mean to dive into tests/ and step through each module as defined (folder by folder), which I believed does what I'm asking above already, but if you part it out module by module, then create an issue per module and throw them all into a 'testing' milestone, you can set a solid stage for testing related work in general. 

Or, take this ball and run with it, think it up, carve it out, keep us informed, the only thing we all care about at the end of the day is adhering to the guidelines set for this total work. Outside of that, ain't no rulebook here :)

**Comment by thejourneydude** [comment]
Good luck!

As an aside, it may be a good idea to draw up a general set of guidelines for writing unit tests in the  Aeon project. That way, when others start writing unit tests, they have a set of guidelines/best practices to follow.

For example, at one of my previous jobs we wrote up a quick section on testing in the Readme file. We provided links to articles on best practices, links to tests within our project that we thought were exemplary tests, special things to consider when testing, etc. This allowed new developers to orient themselves with our project's testing, saved everyone time, and set a standard for writing tests.

Ultimately, this is up to you if you want to do it. I'm not _super_ familiar with C++ testing so seeing a guide like this would make me feel much better, but hey, that's just me. :)

**Comment by guzzijones** [comment]
I am not super familiar either so thanks for your recommendations. I will start on them.

**Comment by drparadoxical** [comment]
In beginning with the Monero tag, we've inadvertently inherited the CONTRIBUTING.md, in which exists strict, yet commonsensical, guidelines. 

@thejourneydude, you may want to start there and see if there's anything that's clearly outside AEON community/development expectations, as well as how we're going to follow suit re: Buildbot, Coveralls, Coverity, and whatever aspects of Github Travis CI are required when gluing this all together. 

I'm of the mind that the document, as is, works just as well here as it has there for Monero dev and developers.

**Comment by thejourneydude** [comment]
I would agree that the CONTRIBUTING.md works well here too. I'll look into this further.

As an aside, there are some clear rules in the CONTRIBUTING.md that we should cover (roles of maintainers, administrators, contributors, etc.) which relates to #11.

**Comment by guzzijones** [comment]
My follow up here is to review contributing.md and return with any changes we need to that doc.  I will be submitting a PR for that specifically if need be.  (clearly there will be if only to change monero to aeon,)

**Comment by drparadoxical** [comment]
For the CONTRIBUTING.md document, I don't see much else to change, and @thejourneydude, the guidelines within this document do partially pertain to us, but I think for our work together here, it's safe to bypass others. For example, we're all in as administrators+contributors here and now, whatever it takes to get the job done, but this repository is ultimately meant to be absorbed by aeonix/aeon through PRs and essentially deprecate itself. 

Unless you had something else in mind, I'm all ears, I've just been operating under the assumption that this, and us, is all here until it's not, because it'll then be over there -> aeonix/aeon.

**Comment by thejourneydude** [comment]
That is a good point Dr. about how this repo will deprecate itself. I was thinking that the CONTRIBUTING.md could be simplified to be more readable for newcomers. But maybe that's not an issue right now because this repo will be deprecated.

The next question to ask is what rules do we keep and what rules do we skip over? Imo, it looks like the following sections work for us:

- General guidelines
- Commits and pull requests
- Specific rules regarding patches and development processes (basic rules for creating/submitting patches)
- Creating stable releases

While other sections should be disregarded:

- Rules regarding how long till merging PRs
- Project Administration
- Roles for administrator, contributor, etc.

I'm sure there are specifics I'm missing as I made a cursory read through the CONTRIBUTING.md doc.

**Comment by drparadoxical** [comment]
My thinking was pretty close to what you just itemized with those two lists, with the only exception being the third point about patches, but only because I doubt we'll run into that. We'll pipeline the commits from aeonix/aeon into the repo and fix/build/test/verify per commit until we're up to the latest Aeon commit, PR that as a single unit of work, or stick to the methodology recently outline and keep it 1:1 when it comes to chaining PRs, even if this one creates quite a few PRs (either of you know which commit, specifically, we'll need to start from - @guzzijones, aren't you a bit more familiar with this territory?) 

But yes sir, no time to linger on PRs as long as we're all fine with a bit of constant vigilance, there is no real manager or administrator outside of the structure and milestones/issues I'm shoving in to serve as a starting point at the very least, and those in on this repo can do whatever they need to do to get it done. If they can't, all they have to do is give us a shout. 

We'll likely see some of the others come back into the mix here over the next day or two, so apologies for being unnecessarily descriptive or obvious with comments this evening, making sure our discussion is easily understood.

**Comment by guzzijones** [comment]
contributing.md works for me.  This repo will be deprecated so no reason to cloud it up with temporary information.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#13
