### ISSUE TITLE
ppl to step up and review pull requests

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#11]
We will need one person at a minimum to step up and review PRS.

**Comment by drparadoxical** [comment]
When it comes to PR review, which is ultimately open to all and excludes no one, I'll step up to that. 

Also assume that whatever it is, whatever unit of work, that isn't done or covered by someone else, will be done by me. 

If integration/merge related work becomes too heavy, we'll cross that bridge when we get there. I'll be keeping one hand down deep in this work, the other up top making sure the pieces keep fitting together correctly, accordingly.

**Comment by thejourneydude** [comment]
I'm happy to help on this as well. Code reviews are one of my strong suits.

If we can get two code reviewers per PR I would be extremely happy. Obviously, anyone else is welcome to review code too and if things get hairy and we only have one code reviewer, I'm ok with that too.

**Comment by guzzijones** [comment]
I think we have a good concensus here.  You two can fight it out. :)

**Comment by drparadoxical** [comment]
CONTRIBUTING.md speaks to this, and while we'll have to route around certain rules (we're moving quickly, so reviewing a PR here cannot sit for a week, we need to develop, test, issue PR, review in parallel to subsequent dev). 

Informally, for now, I think PRs do need at least two people who intelligently reviewed any given PR, s.t. one serves as the red team and the other as blue. Red team should try to find any reason whatsoever the PR isn't sufficient enough as is, and blue team should see if it's sufficient enough due to their being no glaring red flags. 

In the interest of time and sanity, @thejourneydude, we can swap roles on each PR as it occurs. I'll start red, you be blue, next PR I'm blue and you're red, and so on. That'll keep either of us from being burned at the stake, as the red team prick often is, and ensure fair shake and minimal bullshit. 

Process, simple, and if agreeable, let's give it a nod and try to stick to it. A simple "me red you blue" whenever a PR is issued will be sufficient. If someone's not gotten the roles correct on any given PR, who cares, keep moving, as again the only reason you swap is to keep that one devil's advocate red team person from turning into the team's pinata punching bag. 

That said, will one of you please explain to me how the owner a repository issues a pull request? my work should go under the same review process, where any of my submissions are inherently me playing blue team having convinced myself it's good to go, but damnit, for the life of me, I just can't find a way for the owner to hold themselves just as accountable as a project's collaborators. 

I do apologize to you gents, don't mean to slow us down. Still a bit taken aback with supposedly needing all these services and sites and whizzing fuzzy bloody bot coffee maker builders. 

Used to be, you just planned carefully and developed correctly. And now I think I may have subscribed to some sex toy site, wouldn't be surprised if something shows up in the mail a week from now, and I'm alright with it, it's just, sheesh, I've never seen so much bloat. But don't mind me, ignore me, we're going to play this by the book and get it done right, I'm just yelling at people to get off my lawn I suppose.

**Comment by thejourneydude** [comment]
In terms of PR reviews, that should work for me. 

It goes without saying, even though each of us do have specific roles, if something is glaringly obvious the other reviewer missed, we should mention it in our review summaries.

---------

What I would do is push a branch that is NOT master up to the Github repository. Then, create a pull request where you are merging your branch with master. I'm sure you know how to do a pull request via the Github UI but I'll post this [article](https://help.github.com/articles/creating-a-pull-request/) here anyways.

**Comment by drparadoxical** [comment]
Arrived at the same conclusion myself, so great. I'll simply create a develop branch for myself, work against it, and issue PRs from there to origin/master so my work's compartmentalized and under the same strict review process. Repeating our words a 3rd time verbatim for myself, have a nasty cold, off kilter due to whatever it is I'm taking. Christmas colored pills, so I said eh, sure, why not.

**Comment by guzzijones** [comment]
Yes create your own devops. Perfect.  Then your work flow is the same as ours.

**Comment by guzzijones** [comment]
I think we are good here. this can be closed in my opinion. :+1:

**Comment by drparadoxical** [comment]
Agreed, thank you gentlemen.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#14
