### ISSUE TITLE
Install and Configure Buildbot et al. on VPS or VM

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#12]
We will need to setup a build not. Every commit should result in buildable runnable code.

**Comment by guzzijones** [comment]
We really should do this before pushing actual code. Smooth mentioned commits must result in workable software. Dr. Ur servers will come in handy here to setup the build not. Pigeons over at xmr has experience doing this so weay be able to get advice from him.

**Comment by drparadoxical** [comment]
I'll take this over. Let me do a deep dive to see how much can be handled by Github CI, and where precisely the need for a VPS to house a test node comes into play, if it even comes into play. 

I still haven't quite wrapped my head around whether the VPS is even necessary, or if an Aeon testnet is already in existence out there in the wild. 

Since you recently picked up the testing work in another issue, let's you and I play this and that tight until we've worked out the kinks. We'll need to meet in the middle when it comes to the unit test work, CI, the understanding that a PR can't be considered until tests verified as passing, and that still slightly ambiguous notion and need of a/the/our Aeon testnet, VPS', etc.

**Comment by drparadoxical** [comment]
I see what you mean now, @guzzijones. Buildbot handles our CI, removing our need for Github CI and, more importantly, focuses on build health per build - the specific thing that is needed for this type of project, no more. I see now why you recommended Coverity as well, addressing that in discussion of its respective issue.

**Comment by drparadoxical** [comment]
Stepping away for the evening, but updating all that an AEON-esque domain name and sufficiently sized VM have both been stamped down, and I've got Buildbot configured enough to feel comfortable leaving it be for the night, but making note of stopping point for both myself and so that you're all aware we've got a VPS and easy to remember endpoint as we move forward. 

https://build.aeon.direct

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#4
