### ISSUE TITLE
getting paid - sign your commits

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#16]
We should create a folder in the repo for public keys.  Everyone should be signing their commits.  This way we can prove to Smooth we did the work.  @drparadoxical should be in charge of verifying fingerprints for pulled pub keys imo.

**Comment by drparadoxical** [comment]
Ah, I was under the impression you wanted to keep yourself somewhat hidden, and was respecting that decision. Now everyone's going to see your utils/gpg_keys/guzzi.asc sir! 

While I'll absolutely support and stay behind whatever it is that ensures transparency and complete visibility to contributors' work, resetting the starting point to be a direct fork of aeonix/aeon-rebase, and kicking PRs up the chain by contributor, was largely due to this very reason - if there's a clear chain and it's obvious a PR came from a contributor fork of this forked repo up and into aeonix/aeon-rebase as a fork, then there's no erasing it or hiding it, it'll be quantifiable and absolutely, unquestionably that person's work.

You all not getting rewarded according to your contributions is something I've already had to show my ass on once, as per the locking down of the repo for a night and asking Smooth for help, which led to additional guidelines about they ultimately deciding contribution and reward upon successful completion of rebase. 

But again, we'll do whatever it takes to ensure transparency, visibility, and fairness. 

Already had my mind made up on paying all involved myself, in the event the team ended up fucked for whatever reason, truth be told.

**Comment by guzzijones** [comment]
Agree, agree, just thought of it as a 'cover your ass' type of thing.

**Comment by drparadoxical** [comment]
Fair enough, still, anonymity is one of those things I'll not tolerate be threatened, and I figured I'd at least just keep quiet and let you remove that GPG key on your own accord if it was, in fact, something you'd rather not have exposed, since it implies you were/are a part of the Monero team on some level. 

I don't give a flying shit, happy to have you aboard, love working with you so far, will likely enjoy all that comes next as well - just so we're clear. 

It was merely a matter and point of respect, nothing more.

**Comment by drparadoxical** [comment]
This issue was moved to drparadoxical/aeon-rebase-1#7
